### ISSUE TITLE
Proxy breaks after a token renew.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [catalinpan/aws-ecr-proxy#7]
The proxy works great on registry in a different account right after the start but as soon as the token is refreshed, the proxy requests are blocked  by ECR with status code 400.  There maybe in issue in the autoupdate script.

**Comment by catalinpan** [comment]
Can I have please some more details about your setup? Have you just start using the container or you are using this for a while and the issue just appeared? Do you have a custom DNS resolver and block the external DNS resolver? 
If you have any logs will be useful to see. I've just tested locally the "latest" tag with a 60 seconds token renewal and the aws-ecr-proxy returned 400 if the container doesn't exist in ECR, no other problems.

**Comment by mikhail-khodorovskiy** [comment]
I found the fix: the renew script never refreshes the token for the case when the registry is in a different account which is the case with my setup:

```
nx_conf=/etc/nginx/nginx.conf

# update the auth token
auth=$(grep  X-Forwarded-User ${nx_conf} | awk '{print $4}'| uniq|tr -d "\n\r")
if [ "$REGISTRY_ID" = "" ]
then 
    token=$(aws ecr get-login --no-include-email | awk '{print $6}')
else
    aws_cli_exec=$(aws ecr get-login --no-include-email --registry-ids $REGISTRY_ID)
    # token refresh I had to add
    token=$(echo "${aws_cli_exec}" | awk '{print $6}')
fi
auth_n=$(echo AWS:${token}  | base64 |tr -d "[:space:]")

sed -i "s|${auth%??}|${auth_n}|g" ${nx_conf}
```

**Comment by catalinpan** [comment]
thanks for spotting and resolving the issue! I've pushed a fix for this. There is now a new version 1.2.1.
